name: HistoricalGeneralized_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: HistoricalGeneralizedTrain
    type: HistoricalMultiCategoryDataset

    category_roots:
      noise:
        dataroot_gt: ../../../data/noise/train/clean
        dataroot_lq: ../../../data/noise/train/degraded

      blur:
        dataroot_gt: ../../../data/blur/train/clean
        dataroot_lq: ../../../data/blur/train/degraded

      fading:
        dataroot_gt: ../../../data/fading/train/clean
        dataroot_lq: ../../../data/fading/train/degraded

      stains:
        dataroot_gt: ../../../data/stains/train/clean
        dataroot_lq: ../../../data/stains/train/degraded

      bleedthrough:
        dataroot_gt: ../../../data/bleedthrough/train/clean
        dataroot_lq: ../../../data/bleedthrough/train/degraded

      random_degradation:
        dataroot_gt: ../../../data/random_degradation/train/clean
        dataroot_lq: ../../../data/random_degradation/train/degraded

    phase: train
    gt_size: 128
    batch_size_per_gpu: 2
    num_worker_per_gpu: 0
    use_augmentation: true

    io_backend:
      type: disk

  val:
    name: HistoricalGeneralizedVal
    type: HistoricalMultiCategoryDataset

    category_roots:
      noise:
        dataroot_gt: ../../../data/noise/val/clean
        dataroot_lq: ../../../data/noise/val/degraded

      blur:
        dataroot_gt: ../../../data/blur/val/clean
        dataroot_lq: ../../../data/blur/val/degraded

      fading:
        dataroot_gt: ../../../data/fading/val/clean
        dataroot_lq: ../../../data/fading/val/degraded

      stains:
        dataroot_gt: ../../../data/stains/val/clean
        dataroot_lq: ../../../data/stains/val/degraded

      bleedthrough:
        dataroot_gt: ../../../data/bleedthrough/val/clean
        dataroot_lq: ../../../data/bleedthrough/val/degraded

      random_degradation:
        dataroot_gt: ../../../data/random_degradation/val/clean
        dataroot_lq: ../../../data/random_degradation/val/degraded

    phase: val
    gt_size: 128
    use_augmentation: false

    io_backend:
      type: disk


network_g:
  type: Restormer
  inp_channels: 1
  out_channels: 1

  dim: 24

  num_blocks:
    - 2
    - 2
    - 2
    - 4

  num_refinement_blocks: 2

  heads:
    - 1
    - 2
    - 4
    - 8

  ffn_expansion_factor: 2.66
  bias: false
  LayerNorm_type: WithBias
  dual_pixel_task: false


path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~


train:
  total_iter: 5000
  warmup_iter: -1

  use_grad_clip: true

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: false

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods:
      - 5000

    restart_weights:
      - 1

    eta_mins:
      - 0.000001

  optim_g:
    type: AdamW
    lr: 0.0002
    weight_decay: 0.0001
    betas:
      - 0.9
      - 0.999

  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean


val:
  window_size: 8
  val_freq: 500
  save_img: false
  rgb2bgr: false
  use_image: false


logger:
  print_freq: 100
  save_checkpoint_freq: 500
  use_tb_logger: false

  wandb:
    project: ~
    resume_id: ~


dist_params:
  backend: gloo
  port: 29500